stages:
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}-test"
  paths:
    - .cargo/registry/cache/
    - .cargo/git/db/
    - target/

run_tests:
  stage: test
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  before_script:
    # Установка фиксированной ночной версии Rust
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2026-01-19
    - source $CARGO_HOME/env
  script:
    - echo "Running cargo test..."
    - cargo test --workspace --verbose